# -*- coding: utf-8 -*-
"""
Created on Fri May 16 10:54:45 2014

@author: Jens Brauer
"""

import ctypes

(OLSS_AD,
OLSS_DA,
OLSS_DIN,
OLSS_DOUT,
OLSS_SRL,
OLSS_CT) = map(ctypes.c_int, range(6))

(OLSSC_MAXSECHANS,
OLSSC_MAXDICHANS,
OLSSC_CGLDEPTH,
OLSSC_NUMFILTERS,
OLSSC_NUMGAINS,
OLSSC_NUMRANGES,
OLSSC_NUMDMACHANS,
OLSSC_NUMCHANNELS,
OLSSC_NUMEXTRACLOCKS,
OLSSC_NUMEXTRATRIGGERS,
OLSSC_NUMRESOLUTIONS,
   
OLSSC_SUP_INTERRUPT,
OLSSC_SUP_SINGLEENDED,
OLSSC_SUP_DIFFERENTIAL,
OLSSC_SUP_BINARY,
OLSSC_SUP_2SCOMP,
OLSSC_SUP_SOFTTRIG,
OLSSC_SUP_EXTERNTRIG,
OLSSC_SUP_THRESHTRIGPOS,
OLSSC_SUP_THRESHTRIGNEG,
OLSSC_SUP_ANALOGEVENTTRIG,
OLSSC_SUP_DIGITALEVENTTRIG,
OLSSC_SUP_TIMEREVENTTRIG,
OLSSC_SUP_TRIGSCAN,
OLSSC_SUP_INTCLOCK,
OLSSC_SUP_EXTCLOCK,
OLSSC_SUP_SWCAL,
OLSSC_SUP_EXP2896,
OLSSC_SUP_EXP727,
OLSSC_SUP_FILTERPERCHAN,
OLSSC_SUP_DTCONNECT,
OLSSC_SUP_FIFO,
OLSSC_SUP_PROGRAMGAIN,
OLSSC_SUP_PROCESSOR,
OLSSC_SUP_SWRESOLUTION,
OLSSC_SUP_CONTINUOUS,
OLSSC_SUP_SINGLEVALUE,
OLSSC_SUP_PAUSE,
OLSSC_SUP_WRPMULTIPLE,
OLSSC_SUP_WRPSINGLE,

OLSSC_SUP_POSTMESSAGE,
OLSSC_SUP_CASCADING,
OLSSC_SUP_CTMODE_COUNT,
OLSSC_SUP_CTMODE_RATE,
OLSSC_SUP_CTMODE_ONESHOT,
OLSSC_SUP_CTMODE_ONESHOT_RPT,

OLSSC_MAX_DIGITALIOLIST_VALUE,
OLSSC_SUP_DTCONNECT_CONTINUOUS,
OLSSC_SUP_DTCONNECT_BURST,
OLSSC_SUP_CHANNELLIST_INHIBIT,
OLSSC_SUP_SYNCHRONOUS_DIGITALIO,
OLSSC_SUP_SIMULTANEOUS_START,
OLSSC_SUP_INPROCESSFLUSH,

OLSSC_SUP_RANGEPERCHANNEL,
OLSSC_SUP_SIMULTANEOUS_SH,
OLSSC_SUP_RANDOM_CGL,
OLSSC_SUP_SEQUENTIAL_CGL,
OLSSC_SUP_ZEROSEQUENTIAL_CGL,

OLSSC_SUP_GAPFREE_NODMA,
OLSSC_SUP_GAPFREE_SINGLEDMA,
OLSSC_SUP_GAPFREE_DUALDMA,

OLSSCE_MAXTHROUGHPUT,
OLSSCE_MINTHROUGHPUT,
OLSSCE_MAXRETRIGGER,
OLSSCE_MINRETRIGGER,
OLSSCE_MAXCLOCKDIVIDER,
OLSSCE_MINCLOCKDIVIDER,
OLSSCE_BASECLOCK,

OLSSCE_RANGELOW,
OLSSCE_RANGEHIGH,
OLSSCE_FILTER,
OLSSCE_GAIN,
OLSSCE_RESOLUTION, 

OLSSC_SUP_PLS_HIGH2LOW,      
OLSSC_SUP_PLS_LOW2HIGH,      

OLSSC_SUP_GATE_NONE,         
OLSSC_SUP_GATE_HIGH_LEVEL,
OLSSC_SUP_GATE_LOW_LEVEL,    
OLSSC_SUP_GATE_HIGH_EDGE,    
OLSSC_SUP_GATE_LOW_EDGE,     
OLSSC_SUP_GATE_LEVEL,     
OLSSC_SUP_GATE_HIGH_LEVEL_DEBOUNCE,
OLSSC_SUP_GATE_LOW_LEVEL_DEBOUNCE,    
OLSSC_SUP_GATE_HIGH_EDGE_DEBOUNCE,    
OLSSC_SUP_GATE_LOW_EDGE_DEBOUNCE,     
OLSSC_SUP_GATE_LEVEL_DEBOUNCE,

OLSS_SUP_RETRIGGER_INTERNAL,
OLSS_SUP_RETRIGGER_SCAN_PER_TRIGGER,

OLSSC_MAXMULTISCAN,
OLSSC_SUP_CONTINUOUS_PRETRIG,
OLSSC_SUP_CONTINUOUS_ABOUTTRIG, 
OLSSC_SUP_BUFFERING,
OLSSC_SUP_RETRIGGER_EXTRA,

OLSSC_NONCONTIGUOUS_CHANNELNUM,
OLSSC_SUP_SINGLEVALUE_AUTORANGE,
OLSSC_SUP_CTMODE_UP_DOWN,
OLSSC_SUP_CTMODE_MEASURE,
OLSSC_SUP_WRPWAVEFORM,
OLSSC_FIFO_SIZE_IN_K,
OLSSC_SUP_SIMULTANEOUS_CLOCKING,
OLSSC_SUP_FIXED_PULSE_WIDTH,
OLSSC_SUP_QUADRATURE_DECODER,
OLSSC_SUP_CTMODE_CONT_MEASURE,
OLSSC_SUP_AC_COUPLING,
OLSSC_SUP_DC_COUPLING,
OLSSC_SUP_EXTERNAL_EXCITATION_CURRENT_SOURCE,
OLSSC_SUP_INTERNAL_EXCITATION_CURRENT_SOURCE,
OLSSC_EXCITATION_CURRENT_VALUE,					# NOT USED
OLSSC_NUM_EXCITATION_CURRENT_VALUES,				# NOT USED
OLSSC_SUP_WRPWAVEFORM_ONLY,
OLSSC_SUP_INTERLEAVED_CJC_IN_STREAM,
OLSSC_SUP_THERMOCOUPLES,
OLSSC_SUP_TEMPERATURE_DATA_IN_STREAM,
OLSSC_SUP_CJC_SOURCE_CHANNEL,
OLSSC_SUP_CJC_SOURCE_INTERNAL,
OLSSCE_CJC_MILLIVOLTS_PER_DEGREE_C,		# double	
OLSSC_RETURNS_FLOATS,
OLSSC_CURRENT_OUTPUTS,
OLSSC_SUP_PUT_SINGLE_VALUES,
OLSSC_SUP_SV_POS_EXTERN_TTLTRIG,
OLSSC_SUP_SV_NEG_EXTERN_TTLTRIG,
OLSSC_SUP_AUTO_CALIBRATE,
OLSSC_SUP_RTDS,
OLSSC_RETURNS_OHMS,
OLSSC_SUP_SYNCHRONIZATION,
OLSSC_SUP_TEMP_FILTERS) = map(ctypes.c_int, range(126))

OL_CHNT_SINGLEENDED = 100
OL_CHNT_DIFFERENTIAL = 101
OL_ENC_BINARY = 200
OL_ENC_2SCOMP = 201
OL_TRG_SOFT = 300
OL_TRG_EXTERN = 301
OL_TRG_THRESH = 302
OL_TRG_ANALOGEVENT = 303
OL_TRG_DIGITALEVENT = 304
OL_TRG_TIMEREVENT = 305
OL_TRG_EXTRA = 306
OL_CLK_INTERNAL = 400
OL_CLK_EXTERNAL = 401
OL_CLK_EXTRA = 402
OL_GATE_NONE = 500
OL_GATE_HIGH_LEVEL = 501
OL_GATE_LOW_LEVEL = 502
OL_GATE_HIGH_EDGE = 503
OL_GATE_LOW_EDGE = 504
OL_GATE_LEVEL = 505
OL_GATE_HIGH_LEVEL_DEBOUNCE = 506
OL_GATE_LOW_LEVEL_DEBOUNCE = 507
OL_GATE_HIGH_EDGE_DEBOUNCE = 508
OL_GATE_LOW_EDGE_DEBOUNCE = 509
OL_GATE_LEVEL_DEBOUNCE = 510
OL_PLS_HIGH2LOW = 600
OL_PLS_LOW2HIGH = 601
OL_CTMODE_COUNT = 700
OL_CTMODE_RATE = 701
OL_CTMODE_ONESHOT = 702
OL_CTMODE_ONESHOT_RPT = 703
OL_CTMODE_UP_DOWN = 704
OL_CTMODE_MEASURE = 705
OL_CTMODE_CONT_MEASURE = 706
OL_GATE_RISING = 750
OL_GATE_FALLING = 751
OL_CLOCK_RISING = 752
OL_CLOCK_FALLING = 753
OL_DF_CONTINUOUS = 800
OL_DF_SINGLEVALUE = 801
OL_DF_DTCONNECT_CONTINUOUS = 802
OL_DF_DTCONNECT_BURST = 803
OL_DF_CONTINUOUS_PRETRIG = 804
OL_DF_CONTINUOUS_ABOUTTRIG = 805
OL_CT_CASCADE = 900
OL_CT_SINGLE = 901
OL_WRP_NONE = 1000
OL_WRP_MULTIPLE = 1001
OL_WRP_SINGLE = 1002
OL_QUE_READY = 1100
OL_QUE_DONE = 1101
OL_QUE_INPROCESS = 1102
OL_TRG_THRESHPOS = 1200
OL_TRG_THRESHNEG = 1201
OL_RETRIGGER_INTERNAL = 1300
OL_RETRIGGER_SCAN_PER_TRIGGER = 1301
OL_RETRIGGER_EXTRA = 1302
OL_INDEX_DISABLED = 1400
OL_INDEX_LOW = 1401
OL_INDEX_HIGH = 1402
OL_THERMOCOUPLE_TYPE_NONE = 1500
OL_THERMOCOUPLE_TYPE_J = 1501
OL_THERMOCOUPLE_TYPE_K = 1502
OL_THERMOCOUPLE_TYPE_B = 1503
OL_THERMOCOUPLE_TYPE_E = 1504
OL_THERMOCOUPLE_TYPE_N = 1505
OL_THERMOCOUPLE_TYPE_R = 1506
OL_THERMOCOUPLE_TYPE_S = 1507
OL_THERMOCOUPLE_TYPE_T = 1508
OL_RTD_TYPE_VOLTS = 1600
OL_RTD_TYPE_OHMS = 1601
OL_RTD_TYPE_385_EUROPEAN_PT100_OHMS = 1602
OL_RTD_TYPE_385_EUROPEAN_PT500_OHMS = 1603
OL_RTD_TYPE_385_EUROPEAN_PT1000_OHMS = 1604
OL_RTD_TYPE_392_AMERICAN_PT100_OHMS = 1605
OL_RTD_TYPE_392_AMERICAN_PT500_OHMS = 1606
OL_RTD_TYPE_392_AMERICAN_PT1000_OHMS = 1607
OL_TEMP_FILTER_RAW = 1700
OL_TEMP_FILTER_MOVING_AVERAGE = 1701
OL_TEMP_FILTER_QUIET = 1702
OL_TEMP_FILTER_NOMINAL = 1703
OL_POWER_STATE = 100
OL_POWER_OFF = 0
OL_POWER_ON = 1
DONT_UPDATE = 1082163328
DIO_PORT_BASE = 65536
DIO_PORT_CONFIG_OFFSET = 0
DIO_PORT_DATA_OFFSET = 16
DIO_PORT_CONFIG = (DIO_PORT_BASE + DIO_PORT_CONFIG_OFFSET)
DIO_PORT_DATA = (DIO_PORT_BASE + DIO_PORT_DATA_OFFSET)
SMBUS_BUS_BASE = 131072
I2C_BUS_BASE = 262144
USB_BUS_BASE = 524288
FLASH_MEM_BASE = 1048576
EXTERN_MEM_BASE = 2097152
LOCAL_BUS_BASE = 4194304
SUP_GATE_RISING_BIT = 1
SUP_GATE_FALLING_BIT = 2
SUP_CLOCK_RISING_BIT = 4
SUP_CLOCK_FALLING_BIT = 8
MAX_BOARD_NAME_LENGTH = 41
SENSOR_IS_OPEN = 99999.0
TEMP_OUT_OF_RANGE_LOW = (-88888.0)
TEMP_OUT_OF_RANGE_HIGH = 88888.0
OL_SYNC_MODE_NONE = 0
OL_SYNC_MODE_MASTER = 1
OL_SYNC_MODE_SLAVE = 2

#Buffer Codes
WM_USER = 1024  #see http://msdn.microsoft.com/en-us/library/windows/desktop/ms644931(v=vs.85).aspx (#define WM_USER 0x0400) -> 1024 / http://svn.python.org/projects/ctypes/tags/native_pyobjects_from_fields/ctypes/samples/Windows/wtl/windows.py
OLDA_WM_TRIGGER_ERROR     = WM_USER+100
OLDA_WM_UNDERRUN_ERROR    = WM_USER+101
OLDA_WM_OVERRUN_ERROR     = WM_USER+102
OLDA_WM_BUFFER_DONE       = WM_USER+103
OLDA_WM_QUEUE_DONE        = WM_USER+104
OLDA_WM_BUFFER_REUSED     = WM_USER+105
OLDA_WM_QUEUE_STOPPED     = WM_USER+106
OLDA_WM_EVENT_ERROR       = WM_USER+107
OLDA_WM_MEASURE_DONE      = WM_USER+108
OLDA_WM_DTCONNECT_DONE    = WM_USER+109
OLDA_WM_DTCONNECT_STOPPED = WM_USER+110
OLDA_WM_EVENT_DONE        = WM_USER+111
OLDA_WM_PRETRIGGER_BUFFER_DONE  = WM_USER+112
OLDA_WM_DEVICE_REMOVAL    = WM_USER+113
OLDA_WM_IO_COMPLETE       = WM_USER+114

# (WM_USER+200) is reserved in olspi.h for internal driver messages


# Interesting:
#http://code.activestate.com/recipes/208699-calling-windows-api-using-ctypes-and-win32con/
#win32con
#http://pydoc.net/Python/PyZen/0.3.2/pyzen.ui.win32.win32con/